/*
  Prefijos telefónicos de las selecciones del Mundial 2026 (código de país).
  Formato del valor guardado: "+<dial> <numero>".
*/
export const PREFIJOS_TELEFONICOS = [
  { pais: "Uruguay", dial: "598", fifa: "URU" },
  { pais: "Argentina", dial: "54", fifa: "ARG" },
  { pais: "Brasil", dial: "55", fifa: "BRA" },
  { pais: "Chile", dial: "56", fifa: "CHI" },
  { pais: "Paraguay", dial: "595", fifa: "PAR" },
  { pais: "Colombia", dial: "57", fifa: "COL" },
  { pais: "Ecuador", dial: "593", fifa: "ECU" },
  { pais: "Perú", dial: "51", fifa: "PER" },
  { pais: "México", dial: "52", fifa: "MEX" },
  { pais: "Estados Unidos", dial: "1", fifa: "USA" },
  { pais: "Canadá", dial: "1", fifa: "CAN" },
  { pais: "Costa Rica", dial: "506", fifa: "CRC" },
  { pais: "Panamá", dial: "507", fifa: "PAN" },
  { pais: "Honduras", dial: "504", fifa: "HON" },
  { pais: "Jamaica", dial: "1876", fifa: "JAM" },
  { pais: "España", dial: "34", fifa: "ESP" },
  { pais: "Portugal", dial: "351", fifa: "POR" },
  { pais: "Francia", dial: "33", fifa: "FRA" },
  { pais: "Inglaterra", dial: "44", fifa: "ENG" },
  { pais: "Escocia", dial: "44", fifa: "SCO" },
  { pais: "Alemania", dial: "49", fifa: "GER" },
  { pais: "Países Bajos", dial: "31", fifa: "NED" },
  { pais: "Bélgica", dial: "32", fifa: "BEL" },
  { pais: "Italia", dial: "39", fifa: "ITA" },
  { pais: "Croacia", dial: "385", fifa: "CRO" },
  { pais: "Suiza", dial: "41", fifa: "SUI" },
  { pais: "Austria", dial: "43", fifa: "AUT" },
  { pais: "Noruega", dial: "47", fifa: "NOR" },
  { pais: "Suecia", dial: "46", fifa: "SWE" },
  { pais: "Dinamarca", dial: "45", fifa: "DEN" },
  { pais: "Polonia", dial: "48", fifa: "POL" },
  { pais: "Chequia", dial: "420", fifa: "CZE" },
  { pais: "Turquía", dial: "90", fifa: "TUR" },
  { pais: "Bosnia y Herzegovina", dial: "387", fifa: "BIH" },
  { pais: "Marruecos", dial: "212", fifa: "MAR" },
  { pais: "Túnez", dial: "216", fifa: "TUN" },
  { pais: "Argelia", dial: "213", fifa: "ALG" },
  { pais: "Egipto", dial: "20", fifa: "EGY" },
  { pais: "Senegal", dial: "221", fifa: "SEN" },
  { pais: "Ghana", dial: "233", fifa: "GHA" },
  { pais: "Costa de Marfil", dial: "225", fifa: "CIV" },
  { pais: "Sudáfrica", dial: "27", fifa: "RSA" },
  { pais: "Cabo Verde", dial: "238", fifa: "CPV" },
  { pais: "Japón", dial: "81", fifa: "JPN" },
  { pais: "Corea del Sur", dial: "82", fifa: "KOR" },
  { pais: "Irán", dial: "98", fifa: "IRN" },
  { pais: "Arabia Saudita", dial: "966", fifa: "KSA" },
  { pais: "Qatar", dial: "974", fifa: "QAT" },
  { pais: "Jordania", dial: "962", fifa: "JOR" },
  { pais: "Irak", dial: "964", fifa: "IRQ" },
  { pais: "Uzbekistán", dial: "998", fifa: "UZB" },
  { pais: "Australia", dial: "61", fifa: "AUS" },
  { pais: "Nueva Zelanda", dial: "64", fifa: "NZL" },
];
