export const FLAG_IMAGES = {
    ALG: require("../../assets/flags/ALG.png"),
    ARG: require("../../assets/flags/ARG.png"),
    AUS: require("../../assets/flags/AUS.png"),
    AUT: require("../../assets/flags/AUT.png"),
    BEL: require("../../assets/flags/BEL.png"),
    BIH: require("../../assets/flags/BIH.png"),
    BRA: require("../../assets/flags/BRA.png"),
    CAN: require("../../assets/flags/CAN.png"),
    CIV: require("../../assets/flags/CIV.png"),
    COD: require("../../assets/flags/COD.png"),
    COL: require("../../assets/flags/COL.png"),
    CPV: require("../../assets/flags/CPV.png"),
    CRO: require("../../assets/flags/CRO.png"),
    CUW: require("../../assets/flags/CUW.png"),
    CZE: require("../../assets/flags/CZE.png"),
    ECU: require("../../assets/flags/ECU.png"),
    EGY: require("../../assets/flags/EGY.png"),
    ENG: require("../../assets/flags/ENG.png"),
    ESP: require("../../assets/flags/ESP.png"),
    FRA: require("../../assets/flags/FRA.png"),
    GER: require("../../assets/flags/GER.png"),
    GHA: require("../../assets/flags/GHA.png"),
    HAI: require("../../assets/flags/HAI.png"),
    IRN: require("../../assets/flags/IRN.png"),
    IRQ: require("../../assets/flags/IRQ.png"),
    JOR: require("../../assets/flags/JOR.png"),
    JPN: require("../../assets/flags/JPN.png"),
    KOR: require("../../assets/flags/KOR.png"),
    KSA: require("../../assets/flags/KSA.png"),
    MAR: require("../../assets/flags/MAR.png"),
    MEX: require("../../assets/flags/MEX.png"),
    NED: require("../../assets/flags/NED.png"),
    NOR: require("../../assets/flags/NOR.png"),
    NZL: require("../../assets/flags/NZL.png"),
    PAN: require("../../assets/flags/PAN.png"),
    PAR: require("../../assets/flags/PAR.png"),
    POR: require("../../assets/flags/POR.png"),
    QAT: require("../../assets/flags/QAT.png"),
    RSA: require("../../assets/flags/RSA.png"),
    SCO: require("../../assets/flags/SCO.png"),
    SEN: require("../../assets/flags/SEN.png"),
    SUI: require("../../assets/flags/SUI.png"),
    SWE: require("../../assets/flags/SWE.png"),
    TUN: require("../../assets/flags/TUN.png"),
    TUR: require("../../assets/flags/TUR.png"),
    URU: require("../../assets/flags/URU.png"),
    USA: require("../../assets/flags/USA.png"),
    UZB: require("../../assets/flags/UZB.png"),
};

export const NOMBRE_A_CODIGO = {
    argelia: "ALG",
    argentina: "ARG",
    australia: "AUS",
    austria: "AUT",
    bélgica: "BEL",
    belgica: "BEL",
    "bosnia y herzegovina": "BIH",
    brasil: "BRA",
    canadá: "CAN",
    canada: "CAN",
    "costa de marfil": "CIV",
    "rd congo": "COD",
    "república democrática del congo": "COD",
    colombia: "COL",
    "cabo verde": "CPV",
    croacia: "CRO",
    curazao: "CUW",
    "chequia": "CZE",
    "república checa": "CZE",
    ecuador: "ECU",
    egipto: "EGY",
    inglaterra: "ENG",
    españa: "ESP",
    espana: "ESP",
    francia: "FRA",
    alemania: "GER",
    ghana: "GHA",
    haití: "HAI",
    haiti: "HAI",
    irán: "IRN",
    iran: "IRN",
    irak: "IRQ",
    iraq: "IRQ",
    jordania: "JOR",
    japón: "JPN",
    japon: "JPN",
    "corea del sur": "KOR",
    "arabia saudita": "KSA",
    "arabia saudí": "KSA",
    marruecos: "MAR",
    méxico: "MEX",
    mexico: "MEX",
    "países bajos": "NED",
    "paises bajos": "NED",
    holanda: "NED",
    noruega: "NOR",
    "nueva zelanda": "NZL",
    panamá: "PAN",
    panama: "PAN",
    paraguay: "PAR",
    portugal: "POR",
    catar: "QAT",
    qatar: "QAT",
    sudáfrica: "RSA",
    sudafrica: "RSA",
    escocia: "SCO",
    senegal: "SEN",
    suiza: "SUI",
    suecia: "SWE",
    túnez: "TUN",
    tunez: "TUN",
    turquía: "TUR",
    turquia: "TUR",
    uruguay: "URU",
    "estados unidos": "USA",
    eeuu: "USA",
    uzbekistán: "UZB",
    uzbekistan: "UZB",
};

export function resolverBandera(claveOpcional) {
    if (!claveOpcional) return null;
    const k = String(claveOpcional).trim();
    const up = k.toUpperCase();
    if (FLAG_IMAGES[up]) return { source: FLAG_IMAGES[up], codigo: up };
    const cod = NOMBRE_A_CODIGO[k.toLowerCase()];
    if (cod && FLAG_IMAGES[cod]) return { source: FLAG_IMAGES[cod], codigo: cod };
    return null;
}
